# Host e/n/i Datei

- hosts: host1
  name: host1 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 Address
      copy: 
        src: /home/cumulus/ON-12/practice-02-host-1
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on Host1
      shell: /sbin/ifreload -a

# Host e/n/i Datei

- hosts: host2
  name: host2 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 Address
      copy: 
        src: /home/cumulus/ON-12/practice-02-host-2
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on Host2
      shell: /sbin/ifreload -a
      
      
# Host e/n/i Datei

- hosts: host3
  name: host3 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 Address
      copy: 
        src: /home/cumulus/ON-12/practice-02-host-3
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on Host3
      shell: /sbin/ifreload -a      

# Host e/n/i Datei

- hosts: host4
  name: host4 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 Address
      copy: 
        src: /home/cumulus/ON-12/practice-02-host-4
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on Hos4
      shell: /sbin/ifreload -a

# #################################################################
# #################################################################
# #################################################################

# Leaf1 net del

- hosts: leaf1
  name: Leaf1 
  become: yes
  gather_facts: no
  tasks:
  - name: net del all
    nclu:
      commands:
        - del all
        - commit
      

    
