- hosts: leaf1
  name: configuring of PTM
  become: yes
  gather_facts: no
  tasks:
    - name: PTM
      copy:
        src: /home/cumulus/ON-12/topology.dot
        dest: /etc/ptm.d/topology.dot
        mode: '0644'
        owner: 'root'
        group: 'root'
      notify: restart_ptm

  handlers:
    - name: restart_ptm
      service:
        name=ptmd
        state=restarted
      listen: restart_ptm
